language: r
cache: packages
os: linux
dist: bionic
  
env:
  global:
  - MAKEFLAGS="-j 2"
  
jobs:
  include:
  - r: 3.6
  
install:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_local()'
  
script:
  - if [ $TRAVIS_BRANCH == "wip" ] ; then make html_wip;  fi
  - if [ $TRAVIS_BRANCH == "master" ] ; then make html_master;  fi

after_success:
  - if ([ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "wip" ]) ; then bash deploy.sh;  fi
  - if ([ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ]) ; then bash deploy.sh;  fi


